import { SummaryContext } from "../context/SummaryContext";
// productParametersPrototype - each fields can store an array of spec data
export const productParametersPrototype = {
    materials: [],
    lamination: [],
    orientation: [],
    printing_location: [],
    size: [],
    fold_type: [],
    document_type: [],
    bind_type: [],
    cover_material: [],
    lamination_cover: [],
    pages: [],
    paper_type: [],
    inner_page_print_type: [],
    color: [],
    quantity: [],
    middle_page_print_type: [],
    printing_type: [],
    pad_material: [],
    duplicate_sheet_printing_colour: [],
    duplicate_sheet_colour: [],
    invoice_numbering: [],
    starting_invoice_number: [],
    pad_type: [],
    top_sheet_printing_colour: [],
    finish: [],
    frame_colours: [],
    card_sizes: [],
    card_materials: [],
    envelope_type: [],
    id_card_finish: [],
    attachment_type: [],
    combo_and_material: [],
    decal_sizes: [],
    add_on: [],
    product_type: [],
    thickness: [],
    cap_panels: [],
    cap_colours: [],
    alphabets: [],
    cutting_type: [],
    print_type: [],
    sticker_size: [],
    shape: [],
    customization_type: [],
    sleeve_size: [],
    sleeve_material: [],
    box_size: [],
    print_size: [],
    pouch_type: [],
    pouch_material: [],
    printing_options: [],
    design_colour: [],
    type: [],
    style: [],
    tape_colour: [],
    print_colour: [],
    printing_technology: [],
    printable_area: [],
    bag_fabric: [],
    bag_colour: [],
    print_media: [],
    fabric: [],
    fabric_colour: [],
    front_print_size: [],
    front_design_colour_count: [],
    hoodie_style: [],
    banner_sizes: [],
    standee_type: [],
    plate_size: [],
    stand_size: [],
    mirror_acrylic: [],
    accessories: [],
    frame_styles: [],
    acrylic_sizes: [],
    cover_type: [],
    common_back_designs: [],
    border_colour: [],
    border: []    
  };
  
  // productSpecsPrototype - each fields can store a single spec data
  export const productSpecsPrototype = {
    materials: "",
lamination: "",
orientation: "",
printing_location: "",
size: "",
fold_type: "",
document_type: "",
bind_type: "",
cover_material: "",
lamination_cover: "",
pages: "",
paper_type: "",
inner_page_print_type: "",
color: "",
quantity: "",
middle_page_print_type: "",
printing_type: "",
pad_material: "",
duplicate_sheet_printing_colour: "",
duplicate_sheet_colour: "",
invoice_numbering: "",
starting_invoice_number: "",
pad_type: "",
top_sheet_printing_colour: "",
finish: "",
frame_colours: "",
card_sizes: "",
card_materials: "",
envelope_type: "",
id_card_finish: "",
attachment_type: "",
combo_and_material: "",
decal_sizes: "",
add_on: "",
product_type: "",
thickness: "",
cap_panels: "",
cap_colours: "",
alphabets: "",
cutting_type: "",
print_type: "",
sticker_size: "",
shape: "",
customization_type: "",
sleeve_size: "",
sleeve_material: "",
box_size: "",
print_size: "",
pouch_type: "",
pouch_material: "",
printing_options: "",
design_colour: "",
type: "",
style: "",
tape_colour: "",
print_colour: "",
printing_technology: "",
printable_area: "",
bag_fabric: "",
bag_colour: "",
print_media: "",
fabric: "",
fabric_colour: "",
front_print_size: "",
front_design_colour_count: "",
hoodie_style: "",
banner_sizes: "",
standee_type: "",
plate_size: "",
stand_size: "",
mirror_acrylic: "",
accessories: "",
frame_styles: "",
acrylic_sizes: "",
cover_type: "",
common_back_designs: "",
border_colour: "",
border: ""
  };

  

  // Utility function to extract specification details
  export const extractSpecificationDetails = (specInfo) => {
    return {
    materials: specInfo.materials || '',
      lamination: specInfo.lamination || '',
      orientation: specInfo.orientation || '',
      printing_location: specInfo.printing_location || '',
      size: specInfo.size || '',
      quantity: specInfo.quantity || '',
      fold_type: specInfo.fold_type || '',
      document_type: specInfo.document_type || '',
      bind_type: specInfo.bind_type || '',
      cover_material: specInfo.cover_material || '',
      lamination_cover: specInfo.lamination_cover || '',
      pages: specInfo.pages || '',
      paper_type: specInfo.paper_type || '',
      inner_page_print_type: specInfo.inner_page_print_type || '',
      color: specInfo.color || '',
      middle_page_print_type: specInfo.middle_page_print_type || '',
      printing_type: specInfo.printing_type || '',
      pad_material: specInfo.pad_material || '',
      duplicate_sheet_printing_colour: specInfo.duplicate_sheet_printing_colour || '',
      duplicate_sheet_colour: specInfo.duplicate_sheet_colour || '',
      invoice_numbering: specInfo.invoice_numbering || '',
      starting_invoice_number: specInfo.starting_invoice_number || '',
      pad_type: specInfo.pad_type || '',
      top_sheet_printing_colour: specInfo.top_sheet_printing_colour || '',
      finish: specInfo.finish || '',
      frame_colours: specInfo.frame_colours || '',
      card_sizes: specInfo.card_sizes || '',
      card_materials: specInfo.card_materials || '',
      envelope_type: specInfo.envelope_type || '',
      id_card_finish: specInfo.id_card_finish || '',
      attachment_type: specInfo.attachment_type || '',
      combo_and_material: specInfo.combo_and_material || '',
      decal_sizes: specInfo.decal_sizes || '',
      add_on: specInfo.add_on || '',
      product_type: specInfo.product_type || '',
      thickness: specInfo.thickness || '',
      cap_panels: specInfo.cap_panels || '',
      cap_colours: specInfo.cap_colours || '',
      alphabets: specInfo.alphabets || '',
      cutting_type: specInfo.cutting_type || '',
      print_type: specInfo.print_type || '',
      sticker_size: specInfo.sticker_size || '',
      shape: specInfo.shape || '',
      customization_type: specInfo.customization_type || '',
      sleeve_size: specInfo.sleeve_size || '',
      sleeve_material: specInfo.sleeve_material || '',
      box_size: specInfo.box_size || '',
      print_size: specInfo.print_size || '',
      pouch_type: specInfo.pouch_type || '',
      pouch_material: specInfo.pouch_material || '',
      printing_options: specInfo.printing_options || '',
      design_colour: specInfo.design_colour || '',
      type: specInfo.type || '',
      style: specInfo.style || '',
      tape_colour: specInfo.tape_colour || '',
      print_colour: specInfo.print_colour || '',
      printing_technology: specInfo.printing_technology || '',
      printable_area: specInfo.printable_area || '',
      bag_fabric: specInfo.bag_fabric || '',
      bag_colour: specInfo.bag_colour || '',
      print_media: specInfo.print_media || '',
      fabric: specInfo.fabric || '',
      fabric_colour: specInfo.fabric_colour || '',
      front_print_size: specInfo.front_print_size || '',
      front_design_colour_count: specInfo.front_design_colour_count || '',
      hoodie_style: specInfo.hoodie_style || '',
      banner_sizes: specInfo.banner_sizes || '',
      standee_type: specInfo.standee_type || '',
      plate_size: specInfo.plate_size || '',
      stand_size: specInfo.stand_size || '',
      mirror_acrylic: specInfo.mirror_acrylic || '',
      accessories: specInfo.accessories || '',
      frame_styles: specInfo.frame_styles || '',
      acrylic_sizes: specInfo.acrylic_sizes || '',
      cover_type: specInfo.cover_type || '',
      common_back_designs: specInfo.common_back_designs || '',
      border_colour: specInfo.border_colour || '',
      border: specInfo.border || ''
    };
  };
  


  export const clearSummaryDataLoader = () => {
    localStorage.removeItem('summaryData');
    return null; // No data needs to be returned; we're just clearing the storage
  };